### PR TITLE
[DRAFT] Add a rake task to manually audit zip part replication

### PR DESCRIPTION
**Pull request by aaron-collier**
As of the first commit, the is very much a WIP. Pushing this branch and PR up for visibility and recommendations on approach.

### CODE REVIEW

**Comment by jmartin-sul** [comment]
one thought:  if the current part audit code were modified so that the skipping of `unreplicated` parts was optional, you could just run that job synchronously, without having to reproduce so much of what it does internally inside of this rake task.

or, maybe we should just not filter out `unreplicated` parts from audits in general.  i'm not sure how frequently audit runs on an object that isn't fully replicated, and how much spurious noise it'd add if we didn't skip parts in that state.

**Comment by jmartin-sul** [comment]
i'm thinking specifically of this `:unreplicated` filter in this method:  https://github.com/sul-dlss/preservation_catalog/blob/adf8b59d23be5d9101154abc615b64c55cc9f59a/app/lib/preservation_catalog/s3_audit.rb#L20-L28

**Comment by jmartin-sul** [comment]
if we followed through on the change in this branch:  https://github.com/sul-dlss/preservation_catalog/compare/check-unreplicated-zip-parts

i believe a lot of the rake task here (and the wiki entry/gist before it) could be replaced by the contents of the body of `PartReplicationAuditJob#perform`, since a lot of the gist/wiki that's being ported was actually just recreating that code, but removing the where clause removed by that branch.

**Comment by aaron-collier** [comment]
@jmartin-sul - yeah, I was thinking the same thing. After the above work, this is likely unnecessary (or can be cleaned up to call the proper code). There really isn't any reason this shouldn't be part of audit, and allow some automated clean up (i.e. we can determine if the endpoints look correct and the DB just needs to be updated like we have done manually...)

**Comment by ndushay** [comment]
@jmartin-sul 
- do we now have this capability?  
- If we need this, does it warrant a ticket?
- is this PR worth keeping, or have all the refactors made it no longer useful?

**Pull request closed without merging**
