### PR TITLE
DB/README

### PR DESCRIPTION
**Pull request by SaravShah**
Fixed and edited existing readme. Didn't change the transaction, cause I don't think that has changed? Should I remove this section, due to @atz transaction changes in #1030?

Paired w/ @jermnelson 

connects #792

### CODE REVIEW

**Comment by atz** [comment]
Unsure, it seems like a lot of this is just "ActiveRecord 101 Tutorial" and doesn't belong as documentation of this particular app.

**Comment by SaravShah** [comment]
@atz yeah thats what I'm thinking. Maybe i'll remove it. What do other devs think?

**Comment by jmartin-sul** [comment]
i'd be in favor of leaving transaction advice, but i have no objections to a little ActiveRecord 101 in an app that uses ActiveRecord heavily.  ideally we'd all be super-familiar with the tools at hand when being put on a given project, but i don't think that's actually a realistic expectation given our track record as a department, so denormalizing a bit of the relevant documentation from the wider internet seems like a pragmatically good move to me.

**Comment by atz** [comment]
I think we can defer the proviso about "use AR transactionality as much as you want, roll your own as little as possible" to a follow-up.

**Pull request merged**
