### PR TITLE
Add MOAB_CHECKSUM_VALID code

### LINKED ISSUE #596: (CV) Create a success result code in AuditResults for ChecksumValidator
-  have an AuditResult for checksums passing validation
-  will be nice to have an explicit "it passed" -- not only to make this code clearer, but to make it easier for any ReST hookups and log perusing.

### PR DESCRIPTION
**Pull request by tallenaz**
for when a moab passes CV
  ~~also adds a skipped test as a reminder~~
  set up `validate_checksum` method and specs

wait till #594  is merge (still needs to rebase off master too)

  connects #596

### CODE REVIEW

**Comment by tallenaz** [comment]
Not sure either, but my first thought was that the existing `validate_checksum` method would use it, since I imagine we're going to use it to call the manifest inventory and signature catalog methods, but I'm speculating...

**Comment by SaravShah** [comment]
Should we wait to merge this, and have this PR be the PR that implements it into manifestInventory (once PR#591 is merged ofcourse)????

**Comment by tallenaz** [comment]
If we use `ChecksumValidator#checksum_validate` (I guess as a method to wrap `validate_manifest_inventories` and `validate_signature_catalog`), then would this new `MOAB_CHECKSUM_VALID` live there?

**Comment by SaravShah** [comment]
i think this can actually be merged by itself? my PR # 606 ) is rebased off this

**Pull request merged**
