### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by sul-devops-team**

### CODE REVIEW

**Comment by jmartin-sul** [comment]
if the somewhat odd usage of classes as enum values doesn't work with this latest rails update, and if this is also not what you want to dive into fixing right now, i think it's prob fine to pin rails for a bit and file a ticket to circle back on this (maybe on the infra prod priorities board).

i think we realized after not too long that we might've been a little too clever for our own good with that implementation detail, but since it hadn't really bitten us so far, we never bothered to back out of it.  but if it's preventing us from updating dependencies, this might be a good nudge to tweak the implementation.

**Review by jmartin-sul — APPROVED** [review]
LGTM.  slight pref for doing a quick smoke test on stage before deploying to prod.  but if you want to get it merged and get deployments out of the way, i'm also happy to treat that as more of a formality.  if delivery is in fact busted, we'll have a bunch of failed resque jobs we can retry pretty easily.  and the replication integration tests in the code base give me decent confidence that passing tests indicate all is well.

**Review by justinlittman — APPROVED** [review]
Approved by automated merge script

**Comment by jmartin-sul** [comment]
tested on stage, all seems well.  i ran the create_object_no_files_spec.rb and tests from infra integration tests, creating druids vb604zp3555 and yk611qj3118.  there was also a failed delivery from a few days ago for a large moab (3 zip parts per endpoint, qn983fb8749, about 29.8 GB).  i looked at all the expected replicated versions using the documentation here: https://github.com/sul-dlss/preservation_catalog/wiki/Investigating-a-druid-with-replication-errors

all parts seemed to be replicated to all endpoints as expected.

https://argo-stage.stanford.edu/view/druid:vb604zp3555
https://argo-stage.stanford.edu/view/druid:yk611qj3118
https://argo-stage.stanford.edu/view/druid:qn983fb8749

output from the test script from that wiki link:
```
** bucket info:  #<Aws::S3::Bucket:0x00000000081f5ce0 @name="sul-sdr-aws-us-east-1-test", @data=nil, @client=#<Aws::S3::Client>, @waiter_block_warned=false, @resolved_region="us-east-1", @arn=nil>
   ** part info:  Key = qn/983/fb/8749/qn983fb8749.v0001.z01 Found = true
   ** part info:  Key = qn/983/fb/8749/qn983fb8749.v0001.z02 Found = true
   ** part info:  Key = qn/983/fb/8749/qn983fb8749.v0001.zip Found = true
** bucket info:  #<Aws::S3::Bucket:0x0000000004da4630 @name="sul-sdr-aws-us-west-2-test", @data=nil, @client=#<Aws::S3::Client>, @waiter_block_warned=false, @resolved_region="us-west-2", @arn=nil>
   ** part info:  Key = qn/983/fb/8749/qn983fb8749.v0001.z01 Found = true
   ** part info:  Key = qn/983/fb/8749/qn983fb8749.v0001.z02 Found = true
   ** part info:  Key = qn/983/fb/8749/qn983fb8749.v0001.zip Found = true
** bucket info:  #<Aws::S3::Bucket:0x0000000006413b50 @name="sul-sdr-ibm-us-south-1-test", @data=nil, @client=#<Aws::S3::Client>, @waiter_block_warned=false, @resolved_region="us-south", @arn=nil>
   ** part info:  Key = qn/983/fb/8749/qn983fb8749.v0001.z01 Found = true
   ** part info:  Key = qn/983/fb/8749/qn983fb8749.v0001.z02 Found = true
   ** part info:  Key = qn/983/fb/8749/qn983fb8749.v0001.zip Found = true
** bucket info:  #<Aws::S3::Bucket:0x0000000004c8cec8 @name="sul-sdr-aws-us-east-1-test", @data=nil, @client=#<Aws::S3::Client>, @waiter_block_warned=false, @resolved_region="us-east-1", @arn=nil>
   ** part info:  Key = vb/604/zp/3555/vb604zp3555.v0001.zip Found = true
** bucket info:  #<Aws::S3::Bucket:0x0000000008bf4e58 @name="sul-sdr-aws-us-west-2-test", @data=nil, @client=#<Aws::S3::Client>, @waiter_block_warned=false, @resolved_region="us-west-2", @arn=nil>
   ** part info:  Key = vb/604/zp/3555/vb604zp3555.v0001.zip Found = true
** bucket info:  #<Aws::S3::Bucket:0x0000000008ad9ac8 @name="sul-sdr-ibm-us-south-1-test", @data=nil, @client=#<Aws::S3::Client>, @waiter_block_warned=false, @resolved_region="us-south", @arn=nil>
   ** part info:  Key = vb/604/zp/3555/vb604zp3555.v0001.zip Found = true
** bucket info:  #<Aws::S3::Bucket:0x00000000089cb078 @name="sul-sdr-aws-us-east-1-test", @data=nil, @client=#<Aws::S3::Client>, @waiter_block_warned=false, @resolved_region="us-east-1", @arn=nil>
   ** part info:  Key = vb/604/zp/3555/vb604zp3555.v0002.zip Found = true
** bucket info:  #<Aws::S3::Bucket:0x00000000088b5738 @name="sul-sdr-aws-us-west-2-test", @data=nil, @client=#<Aws::S3::Client>, @waiter_block_warned=false, @resolved_region="us-west-2", @arn=nil>
   ** part info:  Key = vb/604/zp/3555/vb604zp3555.v0002.zip Found = true
** bucket info:  #<Aws::S3::Bucket:0x00000000087a2710 @name="sul-sdr-ibm-us-south-1-test", @data=nil, @client=#<Aws::S3::Client>, @waiter_block_warned=false, @resolved_region="us-south", @arn=nil>
   ** part info:  Key = vb/604/zp/3555/vb604zp3555.v0002.zip Found = true
** bucket info:  #<Aws::S3::Bucket:0x0000000008698158 @name="sul-sdr-aws-us-east-1-test", @data=nil, @client=#<Aws::S3::Client>, @waiter_block_warned=false, @resolved_region="us-east-1", @arn=nil>
   ** part info:  Key = yk/611/qj/3118/yk611qj3118.v0001.zip Found = true
** bucket info:  #<Aws::S3::Bucket:0x000000000856e778 @name="sul-sdr-aws-us-west-2-test", @data=nil, @client=#<Aws::S3::Client>, @waiter_block_warned=false, @resolved_region="us-west-2", @arn=nil>
   ** part info:  Key = yk/611/qj/3118/yk611qj3118.v0001.zip Found = true
** bucket info:  #<Aws::S3::Bucket:0x00000000084c7978 @name="sul-sdr-ibm-us-south-1-test", @data=nil, @client=#<Aws::S3::Client>, @waiter_block_warned=false, @resolved_region="us-south", @arn=nil>
   ** part info:  Key = yk/611/qj/3118/yk611qj3118.v0001.zip Found = true
```

**Pull request merged**
