### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by sul-devops-team**

### CODE REVIEW

**Comment by jmartin-sul** [comment]
looks like some brittle user agent specification in a couple stubbed requests are causing the tests failures.  shouldn't be hard to fix.

e.g.:
https://travis-ci.org/sul-dlss/preservation_catalog/jobs/505915123#L725
```
  1) WorkflowReporter.report_error returns true
     Failure/Error: Dor::WorkflowService.update_workflow_error_status(DOR, "druid:#{druid}", PRESERVATIONAUDITWF, process_name, error_message)
     WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: PUT https://workflows.example.org/workflow/dor/objects/druid:jj925bx9565/workflows/preservationAuditWF/moab-valid with body '<?xml version="1.0"?>
       <process name="moab-valid" status="error" errorMessage="Invalid moab, validation error...ential version directories."/>
       ' with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Connection'=>'keep-alive', 'Content-Type'=>'application/xml', 'Keep-Alive'=>'30', 'User-Agent'=>'dor-workflow-service 2.10.0'}
       You can stub this request with the following snippet:
       stub_request(:put, "https://workflows.example.org/workflow/dor/objects/druid:jj925bx9565/workflows/preservationAuditWF/moab-valid").
         with(
           body: "<?xml version=\"1.0\"?>\n<process name=\"moab-valid\" status=\"error\" errorMessage=\"Invalid moab, validation error...ential version directories.\"/>\n",
           headers: {
       	  'Accept'=>'*/*',
       	  'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
       	  'Connection'=>'keep-alive',
       	  'Content-Type'=>'application/xml',
       	  'Keep-Alive'=>'30',
       	  'User-Agent'=>'dor-workflow-service 2.10.0'
           }).
         to_return(status: 200, body: "", headers: {})
       registered request stubs:
       stub_request(:put, "https://workflows.example.org/workflow/dor/objects/druid:jj925bx9565/workflows/preservationAuditWF/moab-valid").
         with(
           body: "<?xml version=\"1.0\"?>\n<process name=\"moab-valid\" status=\"error\" errorMessage=\"Invalid moab, validation error...ential version directories.\"/>\n",
           headers: {
       	  'User-Agent'=>'Faraday v0.15.4'
           })
       ============================================================
     # ./app/services/workflow_reporter.rb:12:in `report_error'
     # ./spec/services/workflow_reporter_spec.rb:21:in `block (3 levels) in <top (required)>'
     # ./spec/support/live_s3.rb:8:in `block (2 levels) in <top (required)>'
  2) WorkflowReporter.report_completed returns true
     Failure/Error: Dor::WorkflowService.update_workflow_status(DOR, "druid:#{druid}", PRESERVATIONAUDITWF, process_name, COMPLETED)
     WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: PUT https://workflows.example.org/workflow/dor/objects/druid:jj925bx9565/workflows/preservationAuditWF/preservation-audit with body '<?xml version="1.0"?>
       <process name="preservation-audit" status="completed" elapsed="0"/>
       ' with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Connection'=>'keep-alive', 'Content-Type'=>'application/xml', 'Keep-Alive'=>'30', 'User-Agent'=>'dor-workflow-service 2.10.0'}
       You can stub this request with the following snippet:
       stub_request(:put, "https://workflows.example.org/workflow/dor/objects/druid:jj925bx9565/workflows/preservationAuditWF/preservation-audit").
         with(
           body: "<?xml version=\"1.0\"?>\n<process name=\"preservation-audit\" status=\"completed\" elapsed=\"0\"/>\n",
           headers: {
       	  'Accept'=>'*/*',
       	  'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
       	  'Connection'=>'keep-alive',
       	  'Content-Type'=>'application/xml',
       	  'Keep-Alive'=>'30',
       	  'User-Agent'=>'dor-workflow-service 2.10.0'
           }).
         to_return(status: 200, body: "", headers: {})
       registered request stubs:
       stub_request(:put, "https://workflows.example.org/workflow/dor/objects/druid:jj925bx9565/workflows/preservationAuditWF/preservation-audit").
         with(
           body: "<?xml version=\"1.0\"?>\n<process name=\"preservation-audit\" status=\"completed\" elapsed=\"0\"/>\n",
           headers: {
       	  'User-Agent'=>'Faraday v0.15.4'
           })
```

**Comment by jmartin-sul** [comment]
thanks @jcoyne and @mjgiarlo!

@jcoyne said:
> but the build still failed with other errors. Is this build fragile?

not as far as i know.  build history seems to indicate that your [follow on commit](https://github.com/sul-dlss/preservation_catalog/commit/4e62b28df1f3a26121b6241526d1dbc1af8c96c0) fixed things, and i don't see any subsequent failures in the history.  🤷‍♂️

**Comment by jcoyne** [comment]
It failed and I had to restart 3 builds, but eventually the went green.

**Comment by jmartin-sul** [comment]
ah, ok, my mistake:  i thought travis kept that sort of thing in it's build history, but i guess if you restart it just uses the same history entry.

@jcoyne, do you remember what the failures were?  would be very curious, my recollection is that preservation tests have been pretty stable for a while now.

**Comment by jcoyne** [comment]
Sorry, I don't recall.

**Comment by jmartin-sul** [comment]
no worries

**Pull request merged**
