### PR TITLE
Refactors CompleteMoabHandler.

### PR DESCRIPTION
**Pull request by justinlittman**
refs #1964

## Why was this change made? 🤔
Some day I hope to understand what this class is doing.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, or if it changes code used internally for cloud replication, ***run [integration test create_preassembly_image_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test/blob/main/spec/features/create_preassembly_image_spec.rb) on stage as it tests preservation***, and/or test in stage environment, in addition to specs. The main classes relevant to replication are `ZipmakerJob`, `PlexerJob`, `*DeliveryJob`, `ResultsRecorderJob`, and `DruidVersionZip`; [see here for overview diagram of replication pipeline](https://github.com/sul-dlss/preservation_catalog/blob/main/app/jobs/README.md).⚡

### CODE REVIEW

**Comment by justinlittman** [comment]
Successfully ran `preassembly_image_accessioning_spec`.

**Comment by justinlittman** [comment]
Really all that is happening here is that the 5 methods in `CompleteMoabHandler` (create, create_after_validation, update, update_after_validation, check_existence) are being split into 5 services classes `(CompleteMoabService::*)`

**Comment by mjgiarlo** [comment]
I wonder if we may want to get https://github.com/sul-dlss/preservation_catalog/pull/1953 in before we move this forward, and then rebase this on `main`.

**Comment by justinlittman** [comment]
Rebased after #1953 merged.

**Review by mjgiarlo — APPROVED** [review]

**Pull request merged**
